# Release Drafter config for schuly
name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - type: version-resolver
    semver-increment: major
    when:
      labels:
        - 'major'
        - 'breaking'
  - type: version-resolver
    semver-increment: minor
    when:
      labels:
        - 'feature'
        - 'enhancement'
        - 'minor'
  - type: version-resolver
    semver-increment: patch
    when:
      labels:
        - 'bug'
        - 'bugfix'
        - 'patch'
        - 'hotfix'
        - 'security'
  - type: version-resolver
    semver-increment: patch
  - type: pre-exclude
    when:
      labels:
        - 'skip-changelog'
        - 'dependencies'
  - title: '🚀 Features'
    type: changelog
    when:
      labels:
        - 'feature'
  - title: '✨ Enhancements'
    type: changelog
    when:
      labels:
        - 'enhancement'
  - title: '🛠️ Refactors'
    type: changelog
    when:
      labels:
        - 'refactor'
  - title: '🐛 Bug Fixes'
    type: changelog
    when:
      labels:
        - 'bug'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&`'

no-changes-template: 'No changes in this release.'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

autolabeler:
  - label: 'feature'
    title:
      - '/^feat(\(.+\))?\!?:.+/'
  - label: 'bug'
    title:
      - '/^fix(\(.+\))?\!?:.+/'
  - label: 'breaking'
    title:
      - '/^.+\!:.+/'
  - label: 'documentation'
    title:
      - '/^docs(\(.+\))?\!?:.+/'
    files:
      - '*.md'
      - 'docs/**/*'
  - label: 'test'
    title:
      - '/^test(\(.+\))?\!?:.+/'
    files:
      - 'test/**/*'
      - '**/*_test.dart'
