name: Build and Release Flutter Apps

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: schuly

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.2'
          channel: 'stable'

      - name: Install dependencies
        working-directory: schuly
        run: flutter pub get

      - name: Build APK (prod flavor)
        working-directory: schuly
        run: |
          flutter build apk --release \
            --flavor prod \
            --dart-define=SENTRY_DSN="${{ vars.SENTRY_URL }}" \
            --dart-define=SENTRY_RELEASE="${{ github.ref_name }}" \
            --dart-define=SENTRY_ENVIRONMENT="production"

      - name: Build App Bundle (prod flavor)
        working-directory: schuly
        run: |
          flutter build appbundle --release \
            --flavor prod \
            --dart-define=SENTRY_DSN="${{ vars.SENTRY_URL }}" \
            --dart-define=SENTRY_RELEASE="${{ github.ref_name }}" \
            --dart-define=SENTRY_ENVIRONMENT="production"

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release.apk
          path: schuly/build/app/outputs/flutter-apk/app-prod-release.apk

      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: app-prod-release.aab
          path: schuly/build/app/outputs/bundle/prodRelease/app-prod-release.aab

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            schuly/build/app/outputs/flutter-apk/app-prod-release.apk
            schuly/build/app/outputs/bundle/prodRelease/app-prod-release.aab
          generate_release_notes: true
          draft: false
          prerelease: false