name: Validate Setup

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/**'
      - 'schuly/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.x'
          channel: 'stable'
          cache: true

      - name: Get dependencies
        run: |
          cd schuly
          flutter pub get

      - name: Validate Flutter project
        run: |
          cd schuly
          flutter doctor -v
          flutter --version
          
      - name: Check if project builds
        run: |
          cd schuly
          flutter build apk --debug --verbose

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: schuly/build/app/outputs/flutter-apk/app-debug.apk